### ISSUE TITLE
python3 decode.py SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by robotzheng** [ucam-smt/sgnmt#2]
File "/home/zzt/sgnmt/cam/sgnmt/decoding/core.py", line 939
    (fAcc, _) = reduce(lambda (f1,w1), (f2,w2):(f1*w1 + f2*w2, 1.0), x, (0.0, 1.0))
                              ^
SyntaxError: invalid syntax

**Comment by fstahlberg** [comment]
we currently only support Python 2.7.

Best, Felix

**Comment by robotzheng** [comment]
thanks. Can you give me some decode examples: ensemble tensor2tensor models  with different vocabulary.

**Comment by fstahlberg** [comment]
Small update on this: Python 3 is now supported
