### ISSUE TITLE
How was supplementary/smt.lats_test18 generated?

### ISSUE THREAD

**Issue by ghost** [ucam-smt/sgnmt#7]
The tutorial data has ```supplementary/smt.lats_test18```. 
Could you please show me how to generate them?

**Comment by wjbyrne** [comment]
Hi,

These lattices were generated by a Hiero syntactic SMT system ( see https://ucam-smt.github.io/tutorial/index.html <https://ucam-smt.github.io/tutorial/index.html> ) as described in this paper   https://arxiv.org/abs/1605.04569 <https://arxiv.org/abs/1605.04569> .   Its outside this tutorial. 

I wouldn’t suggest trying to replicate this, but if you wish to generate lattices you could use any phrase-based MT system that either produces lattices directly or deep n-best lists that can be converted into lattices.

Bill
