### ISSUE TITLE
How to produce the “score_lower_bounds_file”

### ISSUE THREAD

**Issue by zekunzhao** [ucam-smt/sgnmt#8]
Hello, 

I want to run the decoder  simplelendfs  but can not figure out how could I generate score_lower_bounds_file? It was said this file should be generated by beam, but how exactly can I get this? I am using PyTorch and code here https://github.com/ucam-smt/sgnmt/blob/master/cam/sgnmt/decoding/dfs.py#L136.

Thanks,
zekun

**Comment by fstahlberg** [comment]
Hi,
the lower bounds file is a plain text file with one score per line. If you use SGNMT to generate this you can use the nbest output format and do something like this:

`cat sgnmt.nbest | uniq -w 5 | awk '{print $NF}'`

Best, Felix
